---
title: "Check Crs Raster Point Issue"
author: "Anna Talucci"
date: "9/27/2021"
output: html_document
---

# Clear workspace

```{r}
rm(list=ls()) 
```

# Packages

```{r include=FALSE}
library(sp)
library(sf)
library(rgdal) # geospatial data
library(raster)
library(rgeos) # GIS Geometry
library(foreign) # deals with dbf files
```


# Define Projections

[Equal Area projection for Russia](https://gis.stackexchange.com/questions/264093/projection-for-russia-map)

+proj=aea +lat_1=50 +lat_2=70 +lat_0=56 +lon_0=100 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs 

```{r}
ea_russia = "+proj=aea +lat_1=50 +lat_2=70 +lat_0=56 +lon_0=100 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs "
```

# Data
## Rasters
```{r}
r1 = raster("../data/dNBRSingleFire/dNBRimg_4148.tif")
```

## Fire perimeters 
```{r}
fires = st_read("../data/NESiberiaFires/NESiberiaFires2020.shp", "NESiberiaFires2020")
```

# Select fire perimeter
```{r}
fire1 = fires %>%
  filter(IDobj==4148)

fire1
```



# Projection & Resolution

## Raster Projection
```{r}
projection(r1)
```

```{r}

# Project Raster
projected_raster <- projectRaster(r1, crs = ea_russia)
```
# Plot to Check
```{r}
plot(projected_raster)
plot(st_geometry(fire1), add=TRUE)
```




# Limit Raster to Fire perimeter
```{r}
crop_r1 = mask(r1, fire1)
```


# Plot to Check
```{r}
plot(crop_r1)
plot(st_geometry(fire1), add=TRUE)
```
