---
title: "dNBR Rasters"
author: "Anna Talucci"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages
```{r}
library(raster)
library(sp)
library(rgdal)
library(ggplot2)
```


```{r}
r1 <- raster("../data/dnbr/dnbrHarmEA_2019-1.tif")
r2 <- raster("../data/dnbr/dnbrHarmEA_2019-2.tif")
r3 <- raster("../data/dnbr/dnbrHarmEA_2019-3.tif")
r4 <- raster("../data/dnbr/dnbrHarmEA_2019-4.tif")

```


```{r}
r1
```
```{r}
fires = readOGR("../data/SelectFires/FiresNstCkmt2019.shp", "FiresNstCkmt2019")
```


```{r}
x = list(r1, r2, r3, r4)
mosaic = do.call(merge, x)
```
```{r}
mosaic
```


https://stackoverflow.com/questions/15876591/merging-multiple-rasters-in-r
mosaic_rasters(gdalfile=all_my_rasts,dst_dataset="MyBigNastyRasty.tif",of="GTiff")
gdalinfo("MyBigNastyRasty.tif")
```{r}
my_window <- extent(1020150, 2610990, 1077570, 2624280)
```
1020150, 2003190, 1641240, 2624280  (xmin, xmax, ymin, ymax)
```{r}
plot(my_window, col=NA)
plot(mosaic,
     breaks = c(-100, 100, 269, 439, 659), 
     col = c("green", "yellow","darkgoldenrod1", "orange", "red"), add=TRUE)
plot(fires, add=TRUE)
```
```{r}
ggplot() + 
  geom_tile(data = mosaic, aes(x=x, y=y)) 
```

**THE END**