---
title: "PatchSummaryByYear"
author: "Anna Talucci"
date: "2/20/2022"
output: html_document
---

# Clear workspace

```{r}
rm(list=ls()) 
```

# Overview


# Packages

```{r}
library(tidyverse)
```


# Data

## Fire data

```{r}
fires = read.csv("../data/NESiberiaFires/NESiberiaFires2020.csv") 
```

## Patches
```{r}
patches2020 = read.csv("../data/2020Patches/Patches2020AreaCore.csv") 
```


```{r}
patch2001 = list.files(path = '../data/PatchSummaryEqualArea/2001Patch', pattern = "csv$", full.names = TRUE)
patch2014 = list.files(path = '../data/PatchSummaryEqualArea/2014Patch', pattern = "csv$", full.names = TRUE)
patch2015 = list.files(path = '../data/PatchSummaryEqualArea/2015Patch', pattern = "csv$", full.names = TRUE)
patch2016 = list.files(path = '../data/PatchSummaryEqualArea/2016Patch', pattern = "csv$", full.names = TRUE)
patch2017 = list.files(path = '../data/PatchSummaryEqualArea/2017Patch', pattern = "csv$", full.names = TRUE)
patch2018 = list.files(path = '../data/PatchSummaryEqualArea/2018Patch', pattern = "csv$", full.names = TRUE)
patch2019 = list.files(path = '../data/PatchSummaryEqualArea/2019Patch', pattern = "csv$", full.names = TRUE)
```

```{r include=FALSE}
stacked_patch2001 <- map_dfr(patch2001, read_csv)
stacked_patch2014 <- map_dfr(patch2014, read_csv)
stacked_patch2015 <- map_dfr(patch2015, read_csv)
stacked_patch2016 <- map_dfr(patch2016, read_csv)
stacked_patch2017 <- map_dfr(patch2017, read_csv)
stacked_patch2018 <- map_dfr(patch2018, read_csv)
stacked_patch2019 <- map_dfr(patch2019, read_csv)
```

# Organize Patch Class Data 
1. Filter - remove fires with scanline error
2. Pivot Wider so each patch metric is a column
```{r}
stacked2001 = stacked_patch2001 %>% mutate(FireYr = "2001")
stacked2014 = stacked_patch2015 %>% mutate(FireYr = "2014")
stacked2015 = stacked_patch2015 %>% mutate(FireYr = "2015")
stacked2016 = stacked_patch2016 %>% mutate(FireYr = "2016")
stacked2017 = stacked_patch2017 %>% mutate(FireYr = "2017")
stacked2018 = stacked_patch2018 %>% mutate(FireYr = "2018")
stacked2019 = stacked_patch2019 %>% mutate(FireYr = "2019")
```

```{r}
head(stacked2001)
head(stacked2014)
head(stacked2015)
head(stacked2016)
head(stacked2017)
head(stacked2018)
head(stacked2019)
```

```{r}
df1 = bind_rows(stacked2001, stacked2014, stacked2015, stacked2016, stacked2017, stacked2018, stacked2019)
```

```{r}

df1
```

# Fire refugia 2020 data
```{r}
patches2020
```
```{r}

fires1 = fires %>% dplyr::select(IDobj, FireYr, EcoCode, ArcSub)
```

```{r}
fire_patch = merge(fires1, patches2020, by=c("IDobj"))
fire_patch

```


```{r}
patches2020_1 = patches2020 %>% mutate(FireYr = "2020") %>%
  filter(class ==1) %>%
  filter(metric=="area") %>%
  group_by(IDobj, FireYr, class) %>% 
  summarise(area_mn = mean(value))

patches2020_1 

```

```{r}
patches2020_1.1 = patches2020 %>% mutate(FireYr = "2020") %>%
  filter(class ==1) %>%
  filter(metric=="area") %>%
  group_by(IDobj, FireYr, class) 

patches2020_1.1 

```
```{r}
eco_arc_sum = fire_patch %>% filter(class==1) %>%
  filter(metric=="area") %>%
  group_by(EcoCode, ArcSub) %>%
  summarise(mean = mean(value),
            min = min(value),
            max = max(value),
            median = median(value),
            sd = sd(value),
            n = n(),
            se = sd / sqrt(n))

eco_arc_sum
```

```{r}
write.csv(eco_arc_sum, '../outputs/SummaryStats/Summary2020EcoArc.csv',  row.names = FALSE)
```


```{r}
df2 = df1 %>% 
  filter(class ==1) %>%
  filter(metric=="area") %>%
  group_by(IDobj, FireYr, class) %>% 
  summarise(area_mn = mean(value))

df2
```

```{r}
df2.1 = df1 %>% 
  filter(class ==1) %>%
  filter(metric=="area") %>%
  group_by(IDobj, FireYr, class) 

df2.1
```
# Combine 2020 with other

```{r}
df3 = bind_rows(patches2020_1, df2)
df3
```

```{r}
df3.1 = bind_rows(patches2020_1.1, df2.1)
df3.1
```

# Summary Stats
```{r}
df1 %>% filter(class==1) %>%
  group_by(FireYr, class, metric) %>%
  summarise(mean = mean(value),
            min = min(value),
            max = max(value),
            median = median(value),
            sd = sd(value),
            n = n(),
            se = sd / sqrt(n))


```
```{r}
df3
```






```{r}
df3.1
```

```{r}
sum_refugia_yr1 = df3.1 %>% 
  filter(class==1) %>%
  filter(metric=="area") %>%
  group_by(FireYr) %>%
  summarise(mean = mean(value),
            min = min(value),
            max = max(value),
            median = median(value),
            sd = sd(value),
            n = n(),
            se = sd / sqrt(n))

sum_refugia_yr1
```


```{r}
write.csv(sum_refugia_yr1, '../outputs/SummaryStats/SummaryStatesRefugiaAreaYear.csv',  row.names = FALSE)
```


```{r}
df3 %>%
  filter(class==1) %>%
  group_by(FireYr) %>%
  ggplot(., aes(x = FireYr, y = area_mn)) +
  geom_boxplot() +
  scale_y_continuous(trans='log10') 
```

```{r}
df1 %>%
  filter(class==1) %>%
  filter(metric=="area") %>%
  group_by(FireYr, IDobj) %>%
  summarise(mean = mean(value)) %>%
  ggplot(., aes(x = FireYr, y = mean)) +
  geom_boxplot() +
  scale_y_continuous(trans='log10') 
```

```{r}
df1 %>% filter(FireYr==2019) %>%
  drop_na()


```