---
title: "Raster to Point Sample"
author: "Anna Talucci"
date: "9/23/2021"
output: html_document
---

# Overview

Convert dnbr raster to points and sample 5% of points for each individual fire, minus the ones removed for scanline error.

# Clear workspace

```{r}
rm(list=ls()) 
```

# Packages

```{r include=FALSE}
library(sp)
library(sf)
library(rgdal) # geospatial data
library(raster)
library(rgeos) # GIS Geometry
library(foreign) # deals with dbf files
```

# Data
## Rasters
```{r}
r1 = raster("../data/UTMImages/dnbr/UTM51/dNBRimg_3880.tif")
```

```{r}
r2 = raster("../data/UTMImages/dnbr/dNBRimg_3880.tif")
```
## Fire perimeters 
```{r}
fires = st_read("../data/FiresUTM/FiresUTM51.shp", "FiresUTM51")
```

# Select fire perimeter
```{r}
fire1 = fires %>%
  filter(IDobj==3880)

fire1
```

# Limit Raster to Fire perimeter
```{r}
crop_r1 = mask(r1, fire1)
```

```{r}
crop_r2 = mask(r2, fire1)
```
# Plot to Check
```{r}
plot(crop_r1)
plot(st_geometry(fire1), add=TRUE)
```


```{r}
plot(crop_r2)
plot(st_geometry(fire1), add=TRUE)
```

# Raster to point
```{r}
point = rasterToPoints(crop_r1, fun=NULL, spatial=TRUE)
point
```


## Convert to sf object
```{r}
point_sf = st_as_sf(point)
point_sf
```

# Sampling

```{r}
set.seed(101)
samplePt = point_sf %>% 
  rename(dnbr=dNBRimg_4148) %>%
  mutate(IDobj=4148) %>%
  sample_frac(0.05)
samplePt
```


```{r}
ggplot(samplePt, aes(x=dnbr)) + geom_histogram() 
```



## Write  to Shapefile
```{r}
st_write(samplePt, "../outputs/RasterToPoint/Points4148.shp", driver="ESRI Shapefile") 
```



