---
title: "Test Single image per fire option"
author: "Anna Talucci"
date: "9/15/2021"
output: html_document
---

# Overview

https://cran.r-project.org/web/packages/landscapemetrics/landscapemetrics.pdf



#Packages
```{r}
library(raster)
library(sp)
library(rgdal)
library(ggplot2)
library(sf)
library(landscapemetrics)
```


```{r}
r1 <- raster("../data/SingleFiredNBR/IMG_NAME2770.tif")
r2 <- raster("../data/SingleFiredNBR/IMG_Binary2770.tif")

```


```{r}
r1
```

```{r}
fires = st_read("../data/NESiberiaFires/NESiberiaFires2020.shp", "NESiberiaFires2020")
```

```{r}
data.frame(unique(fires$IDobj)) %>% 
  write.csv(., '../outputs/UniqueFireIDobj.csv',  row.names = FALSE)
```

```{r}
fire1 = fires %>%
  filter(IDobj==2770)

fire1

```
```{r}
crop_r1 = mask(r1, fire1)
crop_r2 = mask(r2, fire1)
```

```{r}
plot(crop_r1)
plot(st_geometry(fire1), add=TRUE)

```

```{r}
plot(crop_r2)
plot(st_geometry(fire1), add=TRUE)

```

```{r}
landscape = crop_r2
```
```{r}
check_landscape(landscape)

```

```{r}
show_patches(landscape) 
show_cores(landscape)

```

```{r}

lsm_p_perim(landscape)
```

Coefficient of variation of patch area (Area and edge metric)

```{r}
lsm_c_area_cv(landscape, directions = 8)

```

```{r}
lsm_c_area_mn(landscape)
```

Patch core area
```{r}
lsm_p_core(landscape, directions = 8, consider_boundary = FALSE, edge_depth = 1)

```

```{r}
all_patch_metrics = calculate_lsm(landscape, level = "patch", full_name = TRUE)
```

```{r}
landscape %>% 
  calculate_lsm(., level = "patch", full_name = TRUE) %>% 
  mutate(IDobj = 2770) %>% 
  write.csv(., '../outputs/PatchSummary/PatchFire2770.csv',  row.names = FALSE)
```

```{r}
landscape %>% 
  calculate_lsm(., level = "landscape", full_name = TRUE) %>% 
  mutate(IDobj = 2770) %>% 
  write.csv(., '../outputs/PatchSummary/LandscapeFire2770.csv',  row.names = FALSE)
```

```{r}
landscape %>% 
  calculate_lsm(., level = "class", full_name = TRUE) %>% 
  mutate(IDobj = 2770) %>% 
  write.csv(., '../outputs/PatchSummary/ClassFire2770.csv',  row.names = FALSE)
```