---
title: "Spatial Autocorrelation"
author: "Anna Talucci"
date: "2/27/2022"
output: html_document
---

# Load packages
```{r message=FALSE, warning=FALSE}
library(sp)
library(gstat)
library(purrr) # for looping
library(ggplot2)
library(dplyr) 
library(ape)
```

# Data

```{r}
data(meuse)
```

```{r}
head(meuse)
```
```{r}
data = read.csv("../data/CombinedSampledPoints/SampledGEE2001-2020.csv", header=TRUE, sep = ",", strip.white = TRUE)
```

```{r}
data_resid = read.csv("../data/ModelResiduals/BRT1_Residuals.csv", header=TRUE, sep = ",", strip.white = TRUE)
```

```{r}
data
```

```{r}
head(data_resid)
```

```{r}
data1 = data %>% drop_na()
data1
```

```{r}
df2001 = data %>% filter(FireYr==2001)
```

```{r}
variogram(classes~ASPTR+SLPPCT+TPI450+elevation+Rugged, locations = ~longitude+latitude, data = data)

```

## Residuals
```{r}
variogram1 = variogram(residuals~ASPTR+SLPPCT+TPI450+elevation+Rugged, locations = ~longitude+latitude, data = data_resid)


variogram1
```


```{r}
TheVariogramModel1 <- vgm(psill=50000, model="Gau", nugget=0.001, range=2000)
```


```{r}

FittedModel1 <- fit.variogram(variogram1, model=TheVariogramModel1)    
plot(variogram1, model=FittedModel1)
```

# Raw Data
```{r}
variogram2 = variogram(dnbr~ASPTR+SLPPCT+TPI450+elevation+Rugged, locations = ~longitude+latitude, data = data1, alpha = c(0, 45, 90, 135))

```

```{r}
TheVariogramModel2 <- vgm(psill=70000, model="Gau", nugget=0.001, range=2000)
```


```{r}

FittedModel2 <- fit.variogram(variogram2, model=TheVariogramModel2)    
plot(variogram2, model=FittedModel2)
```


```{r}
lznr.dir = variogram(log(zinc)~sqrt(dist), meuse, alpha = c(0, 45, 90, 135))
plot(lznr.dir, lznr.fit, as.table = TRUE)

```